import{spawn}from'node:child_process';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{randomBytes,randomUUID}from'node:crypto';import{DatabaseSync}from'node:sqlite';import assert from'node:assert/strict';
const dir=await mkdtemp(tmpdir()+'/support-'),base='http://127.0.0.1:3228';const server=spawn(process.execPath,['dist/server.mjs'],{env:{...process.env,PORT:'3228',APP_ORIGIN:base,DATA_DIR:dir,ADMIN_TOKEN:randomBytes(32).toString('hex'),WORKER_TOKEN:randomBytes(32).toString('hex')},stdio:'ignore'});let db;
try{for(let i=0;i<60;i++){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}const call=(cookie,p,b,origin=base)=>fetch(base+'/api/'+p,{method:b?'POST':'GET',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:origin},body:b?JSON.stringify(b):undefined});async function account(email){const r=await call('','register',{email,password:'SupportTest12345'});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0],s=await(await call(cookie,'state')).json();return{cookie,id:s.user.id}}
const a=await account('a@test.com'),b=await account('b@test.com'),admin=await account('admin@example.test');db=new DatabaseSync(dir+'/paperdesk.sqlite');db.prepare("UPDATE users SET role='admin' WHERE id=?").run(admin.id);
assert.equal((await call('','support/messages')).status,401);assert.equal((await call(a.cookie,'support/threads')).status,403);assert.equal((await call(b.cookie,'support/messages?customer='+a.id)).status,403);
const body={body:'检测问题 <script>alert(1)</script>',requestId:randomUUID()};for(let i=0;i<2;i++)assert.equal((await call(a.cookie,'support/messages',body)).status,200);
let msgs=await(await call(admin.cookie,'support/messages?customer='+a.id)).json();assert.equal(msgs.messages.length,1);assert.equal(msgs.unread,1);
assert.equal((await call(admin.cookie,'support/messages?customer='+a.id,{body:'客服回复',requestId:randomUUID()},'https://evil.example')).status,403);
assert.equal((await call(admin.cookie,'support/read?customer='+a.id,{lastId:msgs.messages[0].id})).status,200);assert.equal((await call(admin.cookie,'support/messages?customer='+a.id,{body:'客服回复',requestId:randomUUID()})).status,200);
msgs=await(await call(a.cookie,'support/messages')).json();assert.equal(msgs.messages.length,2);assert.equal(msgs.unread,1);assert.equal((await(await call(b.cookie,'support/messages')).json()).messages.length,0);await call(a.cookie,'support/read',{lastId:msgs.messages.at(-1).id});assert.equal((await(await call(a.cookie,'support/messages')).json()).unread,0);if(process.env.PLAYWRIGHT_MODULE){const{createRequire}=await import('node:module');const{chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE);const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});try{const customerContext=await browser.newContext(),adminContext=await browser.newContext();for(const[ctx,account]of [[customerContext,a],[adminContext,admin]])await ctx.addCookies([{name:'pd_session',value:account.cookie.slice('pd_session='.length),url:base}]);const customerPage=await customerContext.newPage(),adminPage=await adminContext.newPage();await customerPage.goto(base);await customerPage.getByRole('button',{name:/联系客服/}).click();await customerPage.getByLabel('输入聊天消息').fill('浏览器测试问题');await customerPage.getByRole('button',{name:'发送',exact:true}).click();await adminPage.goto(base+'/admin');await adminPage.getByRole('button',{name:/a@test.com/}).click();await adminPage.getByText('浏览器测试问题',{exact:true}).waitFor();await adminPage.getByLabel('输入聊天消息').fill('浏览器测试回复');await adminPage.getByRole('button',{name:'发送',exact:true}).click();await customerPage.getByText('浏览器测试回复',{exact:true}).waitFor();await customerPage.screenshot({path:'work/local-preview/support-desktop.png'});await customerPage.setViewportSize({width:390,height:844});await customerPage.waitForTimeout(400);console.log('Dialog bounds',await customerPage.getByRole('dialog').boundingBox());await customerPage.screenshot({path:'work/local-preview/support-mobile.png'});console.log('PASS: browser customer popup → admin receives → reply appears, desktop/mobile screenshots');}finally{await browser.close()}}
console.log('PASS: customer/admin messages, persistence, unread/read, replay deduplication, customer isolation and cross-origin rejection');
}finally{db?.close();server.kill();await new Promise(r=>server.once('exit',r));await rm(dir,{recursive:true,force:true})}
