'use client';
import {PasswordRequests,ResetCustomer} from '@/components/password-help';
import {AdminSupport} from '@/components/support-chat';
import {useEffect,useState} from 'react';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';
export default function Admin(){
 const [user,setUser]=useState<any>(null),[data,setData]=useState<any>(null),[codes,setCodes]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('users'),[query,setQuery]=useState(''),[jobStatus,setJobStatus]=useState('all'),[announcementDraft,setAnnouncementDraft]=useState('');
 async function api(p:string,b?:any){const r=await fetch('/api/'+p,{method:b?'POST':'GET',headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'操作失败');return d}
 async function load(){const s=await api('state');setUser(s.user);setAnnouncementDraft(s.announcement||'');if(s.user?.role==='admin')setData(await api('admin/overview'));else setData(null)}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 const names:any={users:'客户账号',jobs:'检测记录',orders:'支付订单',codes:'CDK 记录',events:'登录活动',ledger:'额度流水'};
 const columns:any={users:{email:'邮箱',role:'角色',balance:'检测余额',created_at:'注册时间'},jobs:{email:'客户',filename:'文稿',status:'状态',ai_score:'AI %',similarity_score:'相似度 %',error:'失败原因',created_at:'提交时间'},orders:{email:'客户',product_name:'套餐',credits:'次数',amount:'金额（分）',status:'状态',created_at:'创建时间'},codes:{reference:'编号（非兑换码）',credits:'次数',redeemed_by:'兑换客户',redeemed_at:'兑换时间',created_at:'生成时间'},events:{email:'客户',action:'活动',created_at:'时间'},ledger:{email:'客户',id:'流水编号',delta:'次数变动',created_at:'时间'}};
 const display=(k:string,v:any)=>v==null?'—':k.endsWith('_at')?new Date(v).toLocaleString('zh-CN'):({admin:'管理员',customer:'客户',register:'注册',login:'登录','admin-created':'管理员创建',completed:'已完成',failed:'失败',processing:'检测中',queued:'排队',paid:'已支付',pending:'待支付'} as any)[v]||String(v);
 const today=new Date(Date.now()+8*3600000).toISOString().slice(0,10);
 const todayCount=data?.dailyStats?.find((r:any)=>r.day===today)?.total||0;
 return <main className="admin-page"><header className="admin-heading"><div><a href="/?view=customer">← 查看客户页面</a><h1>管理后台</h1></div>{user&&<Button variant="outline" onClick={()=>action(async()=>{await api('logout',{});await load()})}>退出登录</Button>}</header>{message&&<p className="notice" role="status">{message}</p>}
 {!user?<section className="form-card"><h2>管理员登录</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await api('login',{email:f.get('email'),password:f.get('password')});await load()})}}><label>邮箱<Input name="email" type="email" autoComplete="username" required/></label><label>密码<Input name="password" type="password" autoComplete="current-password" required/></label><Button disabled={busy}>登录</Button></form></section>:user.role!=='admin'?<p>当前账号没有管理权限，请退出后使用管理员账号登录。</p>:<>
 <AdminSupport/><PasswordRequests/><section className="form-card admin-announcement-settings"><div><h2>系统公告</h2><p>保存后会显示在客户页面顶部；清空后停止显示。</p></div><form onSubmit={e=>{e.preventDefault();action(async()=>{await api('admin/announcement',{content:announcementDraft});setMessage('系统公告已保存，客户页面刷新后可见。')})}}><label htmlFor="system-announcement-content">公告内容</label><textarea id="system-announcement-content" value={announcementDraft} onChange={e=>setAnnouncementDraft(e.target.value)} maxLength={500} rows={3} placeholder="请输入要展示给客户的公告"/><div className="admin-announcement-actions"><span>{announcementDraft.length}/500 字</span><Button disabled={busy} type="submit">保存公告</Button><Button disabled={busy||!announcementDraft} type="button" variant="outline" onClick={()=>action(async()=>{await api('admin/announcement',{content:''});setAnnouncementDraft('');setMessage('系统公告已清空。')})}>清空公告</Button></div></form></section><div className="admin-forms"><section className="form-card"><h2>创建客户账号</h2><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);action(async()=>{await api('admin/users',{email:f.get('email'),password:f.get('password'),credits:Number(f.get('credits'))});form.reset();await load();setMessage('客户账号已创建，请将设置的账号密码提供给客户。')})}}><label>客户邮箱<Input name="email" type="email" required/></label><label>初始密码<Input name="password" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label><label>初始检测次数<Input name="credits" type="number" min="0" max="1000" defaultValue="0" required/></label><Button disabled={busy}>创建账号</Button></form></section>
 <section className="form-card"><h2>生成 CDK</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{const r=await api('admin/codes',{count:Number(f.get('count')),credits:Number(f.get('credits'))});setCodes(r.codes);await load();setMessage('CDK 已生成，请立即复制保存，完整兑换码只展示本次。')})}}><label>生成数量<Input name="count" type="number" min="1" max="100" defaultValue="1" required/></label><label>每码检测次数<Input name="credits" type="number" min="1" max="1000" defaultValue="1" required/></label><Button disabled={busy}>生成兑换码</Button></form>{codes.length>0&&<><textarea aria-label="生成的兑换码" readOnly value={codes.join('\n')} style={{width:'100%',height:120}}/><Button onClick={()=>navigator.clipboard.writeText(codes.join('\n')).then(()=>setMessage('已复制')).catch(()=>setMessage('请手动复制兑换码'))}>复制全部</Button></>}</section></div>
 <section className="form-card admin-records"><div className="admin-toolbar">{Object.entries(names).map(([k,v])=><Button key={k} variant={tab===k?'default':'outline'} onClick={()=>setTab(k)}>{String(v)}</Button>)}<Button disabled={busy} variant="outline" onClick={()=>action(load)}>刷新</Button><details className="admin-daily-stats"><summary>今日检测 {todayCount} 次 · 每日统计</summary><div className="admin-daily-list"><strong>按北京时间统计提交次数</strong>{data?.dailyStats?.length?data.dailyStats.map((r:any)=><div className="admin-daily-row" key={r.day}><span>{r.day}</span><b>{r.total} 次</b><small>完成 {r.completed} · 失败 {r.failed}</small></div>):<p>暂无检测记录</p>}</div></details></div>{tab==='jobs'&&<select className="admin-status-filter" aria-label="筛选任务状态" value={jobStatus} onChange={e=>setJobStatus(e.target.value)}><option value="all">全部状态</option><option value="failed">失败</option><option value="processing">检测中</option><option value="queued">排队</option><option value="completed">已完成</option></select>}<Input aria-label="搜索记录" placeholder="按邮箱、文件名或记录内容搜索" value={query} onChange={e=>setQuery(e.target.value)}/><p>客户最多展示最近 500 个，其他记录最近 200 条；登录活动从本功能启用后记录。</p><div className="admin-table-scroll"><table className="orders-table"><thead><tr>{Object.values(columns[tab]).map((v:any)=><th key={v}>{v}</th>)}{tab==='jobs'&&<th>文件下载</th>}{['users','jobs'].includes(tab)&&<th>操作</th>}</tr></thead><tbody>{(data?.[tab]||[]).filter((r:any)=>tab!=='jobs'||jobStatus==='all'||r.status===jobStatus).filter((r:any)=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map((r:any,i:number)=><tr key={i}>{Object.keys(columns[tab]).map(k=><td key={k} title={typeof r[k]==='string'?r[k]:undefined} className={'admin-cell-'+k}>{display(k,r[k])}</td>)}{tab==='users'&&<td>{r.role==='customer'&&<ResetCustomer id={r.id} email={r.email} onDone={load}/>}</td>}{tab==='jobs'&&<td><div className="admin-file-links">{[['input','原文'],['ai','AI 原始报告'],['similarity','相似度原始报告'],['ai-restyled','AI 重排报告'],['similarity-restyled','相似度重排报告'],['restyled','合并报告']].filter(([type])=>r.files?.includes(type)).map(([type,label])=><a key={type} href={'/api/admin/file/'+r.id+'/'+type}>{label}</a>)}{!r.files?.length&&<span>暂无文件</span>}</div></td>}{tab==='jobs'&&<td>{r.status==='failed'&&<button disabled={busy} className="admin-row-action" onClick={()=>action(async()=>{await api('admin/retry-job',{jobId:r.id});await load();setMessage('已重新排队，本次修复不再扣客户额度。')})}>修复重试</button>}</td>}</tr>)}</tbody></table>{!data?.[tab]?.length&&<p>暂无记录</p>}</div></section></>}
 </main>
}
