'use client';
import {ForgotPassword,ChangeTemporaryPassword} from '@/components/password-help';
import {CustomerSupport} from '@/components/support-chat';
import {useEffect,useState} from 'react';
import {FileText,Eye,EyeOff,Loader2,Plus,ScanLine,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

type User={email:string,id:string,role?:string,must_change_password?:number};type Job={id:string,filename:string,status:string,created_at:number,ai_score:number|null,similarity_score:number|null,error:string|null,layout_version?:number,report_sources?:string|null};
const labels:Record<string,string>={queued:'等待检测',processing:'检测中',completed:'已完成',failed:'检测失败'};
const MAX_UPLOAD_BYTES=10*1024*1024;
export default function Home(){
 const [payMethod,setPayMethod]=useState('wx');
 const [redeemCode,setRedeemCode]=useState('');
 const [requestId,setRequestId]=useState(()=>crypto.randomUUID()),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[tab,setTab]=useState('orders'),[user,setUser]=useState<User|null>(null),[announcement,setAnnouncement]=useState(''),[balance,setBalance]=useState(0),[jobs,setJobs]=useState<Job[]>([]),[orders,setOrders]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[ready,setReady]=useState(false),[showPassword,setShowPassword]=useState(false),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[payment,setPayment]=useState(false),[worker,setWorker]=useState(false);
 async function api(url:string,body?:any){const r=await fetch('/api/'+url,{method:body?'POST':'GET',headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error||'操作失败，请重试');return d;}
 async function load(){try{let d=await api('state');if(d.user?.must_change_password){setUser(d.user);return}if(d.user?.role==='admin'&&new URLSearchParams(location.search).get('view')!=='customer'){location.replace('/admin');return}if(d.user&&(d.paymentConfigured||d.paymentEnabled)){const pending=d.orders.filter((o:any)=>o.provider==='jianpay'&&o.status==='pending').slice(0,3);if(pending.length){await Promise.allSettled(pending.map((o:any)=>api('orders/'+o.id+'/check',{})));d=await api('state')}}setUser(d.user);setAnnouncement(d.announcement||'');setBalance(d.balance);setJobs(d.jobs);setOrders(d.orders);setProducts(d.products);setPayment(d.paymentEnabled);setWorker(d.workerOnline)}catch(e:any){setMessage(e.message)}finally{setReady(true)}}
 useEffect(()=>{const view=new URLSearchParams(location.search).get('view');if(view&&['orders','dashboard','reports'].includes(view))setTab(view);load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:'read_detection_workspace',description:'Read the signed-in user’s current detection balance and report statuses.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(input&&Object.keys(input).length)throw Error('No parameters accepted');const d=await api('state');return {balance:d.balance,jobs:d.jobs}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 const nav=[['orders','兑换与购买'],['dashboard','提交作业'],['reports','作业收件箱']];
 const visibleJobs=jobs.filter(j=>j.filename.toLowerCase().includes(query.toLowerCase())&&(statusFilter==='all'||j.status===statusFilter));
 const brand=<a href="/" className="classic-brand"><span style={{fontSize:40,fontWeight:700,color:"#004451"}}>PaperDesk</span></a>;
 function sourceLabel(j:Job,kind:string){try{const s=JSON.parse(j.report_sources||'null');return s?.[kind]||'ACADEMI.CX（历史记录）'}catch{return '来源待核实'}}
 const notice=message&&<div className="notice" role="status">{message}<button aria-label="关闭提示" onClick={()=>setMessage('')}>×</button></div>;
 if(!ready)return <div className="loading-screen"><Loader2 className="spin"/>正在加载…</div>;
 if(user?.must_change_password)return <ChangeTemporaryPassword onDone={()=>{setUser(null);setMessage('密码已更新，请使用新密码登录。')}}/>;
 if(!user)return <main className="login-screen"><div className="auth-shell"><div className="auth-logo">{brand}</div><section className="login-panel"><h1>{signup?'创建账号':'Log in'}</h1>{notice}<form className="login-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await api(signup?'register':'login',{email:f.get('email'),password:f.get('password')});const session=await api('state');if(session.user?.role==='admin'){location.replace('/admin');return}setTab('orders');await load()})}}><label>Email<Input name="email" type="email" placeholder="Email" autoComplete="email" required/></label><label>Password<span className="password-field"><Input name="password" type={showPassword?'text':'password'} placeholder={signup?'至少 10 位密码':'Password'} minLength={signup?10:1} autoComplete={signup?'new-password':'current-password'} required/><button type="button" aria-label={showPassword?'隐藏密码':'显示密码'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={20}/>:<Eye size={20}/>}</button></span></label><Button type="submit" disabled={busy} className="login-submit">{busy?'请稍候…':signup?'创建账号':'Log In'}</Button></form><div className="login-links"><ForgotPassword/><button onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'已有账号？返回登录':'没有账号？创建账号'}</button></div></section></div></main>;
 return <div className="classic-workspace"><header className="classic-header"><div className="classic-brand-row">{brand}<div className="header-account-group"><CustomerSupport/><div className="classic-utility"><span className="utility-user">{user.email}</span>{user.role==='admin'&&<a className="utility-link" href="/admin">管理后台</a>}<span className="utility-quota">剩余额度 <strong>{balance}</strong></span><span className={'readiness-chip '+(worker?'ready':'')}>{worker?'检测通道在线':'检测通道离线'}</span><button className="utility-link" disabled={busy} onClick={()=>action(async()=>{await api('logout',{});setSignup(false);await load()})}>退出</button></div></div></div><nav className="classic-tabs" aria-label="主导航">{nav.map(([key,name])=><button key={key} className={'classic-tab '+(tab===key?'active':'')} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setMessage('')}}>{name}</button>)}</nav></header>{announcement&&<div className="system-announcement" role="status"><strong>系统公告</strong><span>{announcement}</span></div>}<main className="classic-page"><div className="classic-view"><p className="classic-breadcrumb">现在查看：主页 &gt; {nav.find(x=>x[0]===tab)?.[1]}</p>{notice}
 {tab==='reports'&&<><div className="report-main-head"><h1>文稿检测</h1><Button onClick={()=>setTab('dashboard')}><Plus size={16}/> 提交新作业</Button></div><div className="report-search"><Input aria-label="搜索文稿" placeholder="搜索文稿名称" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="筛选检测状态" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><section className="classic-report-card"><div className="table-shell"><table className="classic-report-table"><thead><tr>{['标题','创建时间','状态','原文','相似度','AI 检测','相似度报告','AI 检测报告',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{!visibleJobs.length?<tr className="empty-row"><td colSpan={9}>{jobs.length?'没有符合条件的报告。':'当前暂无报告记录。'}</td></tr>:visibleJobs.map(j=><tr key={j.id}><td data-label="标题" className="filename">{j.filename}</td><td data-label="创建时间">{new Date(j.created_at).toLocaleString('zh-CN')}</td><td data-label="状态"><span className={'status '+j.status}>{labels[j.status]}</span>{j.error&&<p className="error-detail">{j.error}</p>}</td><td data-label="原文"><a className="download-link" href={'/api/document/'+j.id}>下载</a></td><td data-label="相似度">{j.similarity_score===null?'—':`${j.similarity_score}%`}</td><td data-label="AI 检测">{j.ai_score===null?'—':<>{`${j.ai_score}%`}<small style={{display:'block'}}>{sourceLabel(j,'ai')}</small></>}</td>{[['similarity-restyled','相似度报告'],['ai-restyled','AI 检测报告']].map(([type,title])=><td key={type} data-label={title}>{type==='ai-restyled'&&j.ai_score==null?<span className="muted">—</span>:j.status==='completed'&&j.ai_score==null&&j.similarity_score!==null?(type==='similarity-restyled'?<a className="download-link" href={'/api/report/'+j.id+'/similarity'} target="_blank" rel="noopener noreferrer">下载原版</a>:<span className="muted">—</span>):j.status==='completed'?<a className="download-link" href={'/api/report/'+j.id+'/'+((j.layout_version||0)>=2?type:'restyled')} target="_blank" rel="noopener noreferrer">下载</a>:type==='similarity-restyled'&&j.status==='failed'&&j.similarity_score!==null?<a className="download-link" href={'/api/report/'+j.id+'/similarity'} target="_blank" rel="noopener noreferrer">下载原版</a>:<span className="muted">—</span>}</td>)}<td className="delete-record-cell"><button className="delete-record-button" disabled={busy||!['completed','failed'].includes(j.status)} onClick={()=>action(async()=>{await api('delete-job/'+j.id,{});await load();setMessage('记录已从列表删除。')})}>删除</button></td></tr>)}</tbody></table></div></section></>}
 {tab==='dashboard'&&<form className="classic-submit-card" onSubmit={e=>{e.preventDefault();action(async()=>{if(!file)throw Error('请先选择文稿');if(file.size>MAX_UPLOAD_BYTES)throw Error('文件不能超过 10 MB');const form=new FormData();form.append('file',file);form.append('requestId',requestId);await api('jobs',form);setFile(null);setRequestId(crypto.randomUUID());setQuery('');setStatusFilter('all');setTab('reports');setMessage('已提交，检测完成后可在作业收件箱下载报告。');await load()})}}><div className="classic-card-head"><span>文稿提交：<span className="blue-text">AI 检测与相似度检测</span></span><span>步骤 {file?'●●○':'●○○'}</span></div><div className="classic-card-body"><div className="file-pick-row"><label className="file-button">从电脑选择文件<input type="file" accept=".pdf,.docx" onChange={e=>{const chosen=e.target.files?.[0]||null;setFile(chosen&&chosen.size<=MAX_UPLOAD_BYTES?chosen:null);setMessage(chosen&&chosen.size>MAX_UPLOAD_BYTES?'文件不能超过 10 MB':'');setRequestId(crypto.randomUUID());e.target.value=''}}/></label><span>每次仅提交一个文件。文件类型：docx, pdf。单个不超过 10 MB。</span></div><div className="similarity-upload-requirements" role="note">【相似度检测】语种：不限　字数：不限　单个文件不超过 10 MB</div><div className="ai-upload-requirements" role="note"><strong>【AI 检测】</strong>语种：英语　字数范围：350–29,500 词　单个文件不超过 10 MB</div>{file&&<div className="selected-files-panel"><div><strong>已选择文件</strong><button type="button" onClick={()=>setFile(null)}>移除</button></div><p>{file.name} <span className="muted">（{Math.ceil(file.size/1024)} KB）</span></p><small>请确认文件无误后再上传。</small></div>}</div><div className="classic-card-foot"><p>AI 由 ACADEMI.CX 检测；相似度由 Turnitin（UTAD）检测并返回英文原版报告，按该机构当前设置提交。中文文稿或不在 AI 检测 350–29,500 词范围内的文稿仅做相似度检测并消耗 1 次额度。报告仅对你的账号可见，检测失败自动退还额度。</p><Button type="submit" disabled={busy||!file}>{busy?'正在上传…':'上传'}</Button><Button className="classic-cancel" type="button" variant="outline" onClick={()=>{setFile(null);setTab('reports')}}>取消</Button></div></form>}
 {tab==='orders'&&<><div className="report-main-head"><h1>兑换与购买</h1></div><div className="ai-notice payment-notice">{payment?'购买成功后，检测额度直接增加到当前账号。':'套餐暂未开放购买，请稍后再试。'}</div><div className="payment-method-picker" role="group" aria-label="支付方式"><span>支付方式</span><div className="payment-method-options">{[['alipay','支付宝支付'],['wx','微信支付']].map(([value,label])=><button type="button" key={value} className={'payment-method-option payment-card '+value+' '+(payMethod===value?'selected':'')} aria-label={label} aria-pressed={payMethod===value} disabled={busy} onClick={()=>setPayMethod(value)}><span className="payment-card-head"><span className="payment-check">{payMethod===value&&<Check size={18}/>}</span>{label}</span><span className="payment-card-body"><span className="payment-card-symbols"><span className="payment-official-logo"><img src={value==='alipay'?'/payment/alipay.png':'/payment/wechat-pay.svg'} alt={value==='alipay'?'支付宝官方标志':'微信支付官方标志'}/></span><ScanLine size={30} aria-hidden="true"/></span></span></button>)}</div></div><div className="products">{products.map(p=><section className="product" key={p.id}><h2>{p.name}</h2><p>{p.credits} 次完整检测</p><strong>{p.price?`¥${(p.price/100).toFixed(2)}`:'价格待设置'}</strong><Button disabled={!payment||busy} onClick={()=>action(async()=>{const d=await api('orders',{product:p.id,payMethod});window.open(d.url,'_blank','noopener,noreferrer');await load();setMessage('订单已创建，请在收银台支付；支付后本页会自动查询到账。')})}>购买额度</Button></section>)}</div><section className="cdk-panel" aria-label="CDK 兑换"><form onSubmit={e=>{e.preventDefault();action(async()=>{const result=await api('redeem',{code:redeemCode.trim()});setRedeemCode('');await load();setMessage(`兑换成功，已增加 ${result.credits} 次检测额度。`)})}}><label htmlFor="redeem-code">检测次数 CDK 兑换</label><div className="cdk-input-row"><Input id="redeem-code" placeholder="请输入 CDK 兑换码" autoComplete="off" spellCheck={false} maxLength={100} value={redeemCode} onChange={e=>setRedeemCode(e.target.value)} required/><Button type="submit" disabled={busy||!redeemCode.trim()}>{busy?'处理中…':'兑换'}</Button></div><p>兑换后直接到账，每个兑换码仅限使用一次。</p></form><div className="cdk-balance"><span>检测余额</span><strong>{balance}</strong><small>次</small></div></section><section className="classic-report-card"><table className="orders-table"><thead><tr><th>订单</th><th>创建时间</th><th>支付状态</th><th>到账情况</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id}><td>{o.product_name}</td><td>{new Date(o.created_at).toLocaleString('zh-CN')}</td><td>{o.status==='paid'?'已支付':'待支付'}</td><td>{o.status==='paid'?'额度已到账':<>{o.pay_url&&<a href={o.pay_url} target="_blank" rel="noreferrer">继续支付</a>} <Button disabled={busy} onClick={()=>action(async()=>{const r=await api('orders/'+o.id+'/check',{});setMessage(r.paid?'额度已到账':'尚未确认支付，请稍后刷新')})}>刷新到账</Button></>}</td></tr>):<tr className="empty-row"><td colSpan={4}>当前暂无订单记录。</td></tr>}</tbody></table></section></>}
 </div></main></div>
}
