import {useEffect,useRef,useState} from 'react';
import {MessageCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from './ui/dialog';
type Message={id:number,sender_role:string,body:string,created_at:number};
async function call(path:string,body?:any){const r=await fetch('/api/support/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'连接失败');return d}
function Conversation({customer,admin=false}:{customer?:string,admin?:boolean}){
 const [messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[older,setOlder]=useState(false),[more,setMore]=useState(false);
 const request=useRef(crypto.randomUUID()),end=useRef<HTMLDivElement>(null),box=useRef<HTMLDivElement>(null),nearBottom=useRef(true);
 const query=customer?'?customer='+encodeURIComponent(customer):'';
 useEffect(()=>{let live=true;async function load(){try{const d=await call('messages'+query);if(!live)return;setMessages(prev=>[...prev.filter(x=>d.messages.length&&x.id<d.messages[0].id),...d.messages]);setMore(d.messages.length===100);setError('');if(document.visibilityState==='visible'&&d.messages.length)await call('read'+query,{lastId:d.messages.at(-1).id})}catch(e:any){if(live)setError(e.message)}}load();const timer=setInterval(load,3000);return()=>{live=false;clearInterval(timer)}},[query]);
 useEffect(()=>{if(nearBottom.current)end.current?.scrollIntoView({block:'nearest'})},[messages.length]);
 async function send(e:React.FormEvent){e.preventDefault();if(!draft.trim()||sending)return;setSending(true);setError('');try{await call('messages'+query,{body:draft,requestId:request.current});setDraft('');request.current=crypto.randomUUID();nearBottom.current=true;const d=await call('messages'+query);setMessages(prev=>[...prev.filter(x=>d.messages.length&&x.id<d.messages[0].id),...d.messages])}catch(e:any){setError(e.message)}finally{setSending(false)}}
 return <div className="support-conversation"><div className="support-history" ref={box} onScroll={()=>{const el=box.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<70}} aria-live="polite" role="log" aria-label="聊天记录">
 {more&&messages.length>0&&<button disabled={older} className="support-more" onClick={async()=>{setOlder(true);try{const d=await call('messages'+query+(query?'&':'?')+'before='+messages[0].id);nearBottom.current=false;setMessages(prev=>[...d.messages,...prev]);setMore(d.messages.length===100)}catch(e:any){setError(e.message)}finally{setOlder(false)}}}>查看更早消息</button>}
 {!messages.length&&<p className="support-empty">{admin?'暂无消息':'你好，请描述遇到的问题，客服会在此回复。'}</p>}
 {messages.map(m=><div key={m.id} className={'support-message '+(m.sender_role===(admin?'admin':'customer')?'mine':'')}><small>{m.sender_role==='admin'?'客服':'客户'} · {new Date(m.created_at).toLocaleString('zh-CN')}</small><p>{m.body}</p></div>)}<div ref={end}/></div>
 {error&&<p className="support-error" role="status">{error}，可稍后重试。</p>}
 <form className="support-compose" onSubmit={send}><textarea aria-label="输入聊天消息" placeholder="请输入问题或回复…" maxLength={2000} value={draft} disabled={sending} onChange={e=>{setDraft(e.target.value);request.current=crypto.randomUUID()}}/><button disabled={sending||!draft.trim()}>{sending?'发送中…':'发送'}</button></form><small className="support-hint">消息会保存。客服未及时回复时，可稍后返回查看。</small></div>
}
export function CustomerSupport(){const[open,setOpen]=useState(false),[unread,setUnread]=useState(0);useEffect(()=>{let live=true;async function poll(){try{const d=await call('messages');if(live)setUnread(d.unread)}catch{}}poll();const t=setInterval(poll,5000);return()=>{live=false;clearInterval(t)}},[]);return <Dialog open={open} onOpenChange={v=>{setOpen(v);if(v)setUnread(0)}}><DialogTrigger asChild><button className="support-launch"><MessageCircle size={18}/>联系客服{unread>0&&<b>{unread}</b>}</button></DialogTrigger><DialogContent className="support-dialog"><DialogHeader><DialogTitle>联系客服</DialogTitle><DialogDescription>与网站管理员沟通使用问题</DialogDescription></DialogHeader>{open&&<Conversation/>}</DialogContent></Dialog>}
export function AdminSupport(){const[threads,setThreads]=useState<any[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState('');useEffect(()=>{let live=true;async function poll(){try{const d=await call('threads');if(live){setThreads(d.threads);setError('')}}catch(e:any){if(live)setError(e.message)}}poll();const t=setInterval(poll,4000);return()=>{live=false;clearInterval(t)}},[]);const total=threads.reduce((n,t)=>n+t.unread,0);return <section className="admin-support form-card"><h2>客服消息 {total>0&&<span className="support-badge">{total} 条未读</span>}</h2>{error&&<p role="status">{error}</p>}<div className="support-desk"><aside><input aria-label="搜索客服会话" placeholder="搜索客户邮箱" value={query} onChange={e=>setQuery(e.target.value)}/>{!threads.length&&<p className="support-empty">客户发来消息后，会在这里显示。</p>}{threads.filter(t=>t.email.toLowerCase().includes(query.toLowerCase())).map(t=><button className={selected===t.id?'active':''} key={t.id} onClick={()=>setSelected(t.id)}><strong>{t.email}{t.unread>0&&<b className="support-badge">{t.unread}</b>}</strong><span>{t.preview}</span></button>)}</aside><div className="support-desk-chat">{selected?<><h3>{threads.find(t=>t.id===selected)?.email}</h3><Conversation key={selected} customer={selected} admin/></>:<p className="support-empty">选择客户会话进行回复</p>}</div></div></section>}
